title: de-mpiere
# description: ...

# see https://github.com/pages-themes/architect
theme: jekyll-theme-architect

# to indicate whether to provide a download URL
show_downloads: "false"

google_analytics:

# src nicht in root:
# source: _pages
